name: 微服务CI/CD流水线
on: [push]  # 代码推送时触发

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装Python依赖
        run: |
          cd app
          pip install -r requirements.txt

      - name: 构建Docker镜像（适配Docker 28.x）
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/enterprise-app:${{ github.sha }} ./app

      - name: 登录Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 推送镜像到Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/enterprise-app:${{ github.sha }}
